-- snowflake/import_and_transform.sql
-- Loads data from S3 into COLLATE_SE and computes all derived columns.
-- Designed to be run by run_queries.py as JASON using the SALES_ENGINEERS role.

-- ============================================================
-- 1. SESSION CONTEXT
-- ============================================================
USE ROLE SALES_ENGINEERS;
USE WAREHOUSE DEMO_WH;
USE DATABASE CUSTOMERS;
USE SCHEMA COLLATE_SE;

-- ============================================================
-- 2. CLEAR RAW TABLES
-- ============================================================
TRUNCATE TABLE RAW_CUSTOMERS;
TRUNCATE TABLE RAW_ORDERS;
TRUNCATE TABLE RAW_ORDER_ITEMS;
TRUNCATE TABLE RAW_PRODUCTS;

-- ============================================================
-- 3. LOAD RAW DATA FROM S3  (creates lineage in Collate)
-- ============================================================

-- RAW_CUSTOMERS
COPY INTO RAW_CUSTOMERS
FROM 's3://collate-snowflake-interchange-118146679784/raw_customers_export.csv'
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- RAW_ORDERS
COPY INTO RAW_ORDERS
FROM 's3://collate-snowflake-interchange-118146679784/raw_orders_export.csv'
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- RAW_ORDER_ITEMS
COPY INTO RAW_ORDER_ITEMS
FROM 's3://collate-snowflake-interchange-118146679784/raw_order_items_export.csv'
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- RAW_PRODUCTS
COPY INTO RAW_PRODUCTS
FROM 's3://collate-snowflake-interchange-118146679784/raw_products_export.csv'
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';

-- ============================================================
-- 4. LOAD PRODUCTION TABLES FROM RAW  (creates lineage S3 -> RAW -> PROD)
-- ============================================================

-- CUSTOMERS: Full load in one shot for perfect column-level lineage
TRUNCATE TABLE CUSTOMERS;
INSERT INTO CUSTOMERS (
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, FULL_NAME, PRIORITY_SCORE,
    FIRST_ORDER, MOST_RECENT_ORDER, NUMBER_OF_ORDERS, 
    CUSTOMER_LIFETIME_VALUE, LAST_UPDATE_AT
)
WITH order_aggs AS (
    SELECT
        o.CUSTOMER_ID,
        MIN(o.ORDER_DATE)           AS FIRST_ORDER,
        MAX(o.ORDER_DATE)           AS MOST_RECENT_ORDER,
        COUNT(DISTINCT o.ORDER_ID)  AS NUMBER_OF_ORDERS,
        SUM(oi.TOTAL_AMOUNT)        AS CUSTOMER_LIFETIME_VALUE
    FROM ORDERS o
    LEFT JOIN ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
    GROUP BY o.CUSTOMER_ID
)
SELECT 
    rc.ID AS CUSTOMER_ID,
    rc.FIRST_NAME,
    rc.LAST_NAME,
    CONCAT(rc.FIRST_NAME, ' ', rc.LAST_NAME) AS FULL_NAME,
    CASE 
        WHEN rc.ID < 1000 AND rc.FIRST_NAME IS NOT NULL AND rc.LAST_NAME IS NOT NULL THEN 'High Priority'
        WHEN rc.FIRST_NAME IS NOT NULL AND rc.LAST_NAME IS NOT NULL THEN 'Standard'
        ELSE 'Incomplete Profile'
    END AS PRIORITY_SCORE,
    oa.FIRST_ORDER,
    oa.MOST_RECENT_ORDER,
    COALESCE(oa.NUMBER_OF_ORDERS, 0)      AS NUMBER_OF_ORDERS,
    COALESCE(oa.CUSTOMER_LIFETIME_VALUE, 0) AS CUSTOMER_LIFETIME_VALUE,
    CURRENT_TIMESTAMP()                     AS LAST_UPDATE_AT
FROM RAW_CUSTOMERS rc
LEFT JOIN order_aggs oa ON rc.ID = oa.CUSTOMER_ID;

-- ORDERS: from RAW_ORDERS (updated details below)
TRUNCATE TABLE ORDERS;
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS, 
                    CREDIT_CARD_AMOUNT, COUPON_AMOUNT, BANK_TRANSFER_AMOUNT, GIFT_CARD_AMOUNT, AMOUNT)
WITH order_totals AS (
    SELECT ORDER_ID, SUM(TOTAL_AMOUNT) as TOTAL
    FROM ORDER_ITEMS
    GROUP BY ORDER_ID
)
SELECT 
    ro.ID, 
    ro.USER_ID, 
    ro.ORDER_DATE, 
    ro.STATUS,
    0, 0, 0, 0,
    COALESCE(ot.TOTAL, 0)
FROM RAW_ORDERS ro
LEFT JOIN order_totals ot ON ro.ID = ot.ORDER_ID;

-- ORDER_ITEMS from RAW_ORDER_ITEMS
TRUNCATE TABLE ORDER_ITEMS;
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT
FROM RAW_ORDER_ITEMS;

-- PRODUCTS from RAW_PRODUCTS
TRUNCATE TABLE PRODUCTS;
INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY, ECO_FRIENDLY, UNIT_PRICE)
SELECT PRODUCT_NAME, CATEGORY, ECO_FRIENDLY, UNIT_PRICE
FROM RAW_PRODUCTS;


-- ============================================================
-- 6. SUMMARY TABLES
-- ============================================================
TRUNCATE TABLE CUSTOMER_LIFETIME_VALUE;
INSERT INTO CUSTOMER_LIFETIME_VALUE (CUSTOMER_ID, TOTAL_ORDER, TOTAL_REVENUE, AVERAGE_ORDER_VALUE, SEGMENT)
SELECT CUSTOMER_ID, NUMBER_OF_ORDERS, CUSTOMER_LIFETIME_VALUE, 
       CUSTOMER_LIFETIME_VALUE/NULLIF(NUMBER_OF_ORDERS,0),
       CASE WHEN CUSTOMER_LIFETIME_VALUE > 200 THEN 'Gold' ELSE 'Silver' END
FROM CUSTOMERS;

TRUNCATE TABLE PRODUCT_PERFORMANCE;
INSERT INTO PRODUCT_PERFORMANCE (PRODUCT_ID, PRODUCT_NAME, TOTAL_ORDERS, TOTAL_REVENUE)
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, COUNT(DISTINCT oi.ORDER_ID), SUM(oi.TOTAL_AMOUNT)
FROM PRODUCTS p
LEFT JOIN ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME;
