-- snowflake/rebuild_collate_se.sql
-- Full DDL to recreate COLLATE_SE schema cleanly with correct ownership and no references to COLLATE_SHOP.
-- Run as JASON (or via rebuild_collate_se.py which handles teardown + privilege grants).

-- ============================================================
-- 1. SESSION CONTEXT
-- ============================================================
USE ROLE SALES_ENGINEERS;
USE WAREHOUSE DEMO_WH;
USE DATABASE CUSTOMERS;

-- ============================================================
-- 2. DROP AND RECREATE THE SCHEMA
-- ============================================================
DROP SCHEMA IF EXISTS CUSTOMERS.COLLATE_SE;
CREATE SCHEMA CUSTOMERS.COLLATE_SE;
USE SCHEMA CUSTOMERS.COLLATE_SE;

-- ============================================================
-- 3. RAW TABLES  (sources from S3)
-- ============================================================

CREATE OR REPLACE TABLE COLLATE_SE.RAW_CUSTOMERS (
    ID          NUMBER,
    FIRST_NAME  VARCHAR,
    LAST_NAME   VARCHAR
) COMMENT = 'RAW CUSTOMERS';

CREATE OR REPLACE TABLE COLLATE_SE.RAW_ORDERS (
    ID          NUMBER,
    USER_ID     NUMBER,
    ORDER_DATE  DATE,
    STATUS      VARCHAR
);

CREATE OR REPLACE TABLE COLLATE_SE.RAW_ORDER_ITEMS (
    ORDER_ITEM_ID   NUMBER,
    ORDER_ID        NUMBER,
    PRODUCT_ID      NUMBER,
    QUANTITY        NUMBER,
    UNIT_PRICE      NUMBER(10,2),
    TOTAL_AMOUNT    NUMBER(10,2)
);

CREATE OR REPLACE TABLE COLLATE_SE.RAW_PRODUCTS (
    PRODUCT_ID      NUMBER,
    PRODUCT_NAME    VARCHAR,
    CATEGORY        VARCHAR,
    ECO_FRIENDLY    BOOLEAN,
    UNIT_PRICE      NUMBER(10,2)
);

-- ============================================================
-- 4. PRODUCTION TABLES
-- ============================================================

-- COMMENT preserved from COLLATE_SHOP: "new 'description'"
CREATE OR REPLACE TRANSIENT TABLE COLLATE_SE.CUSTOMERS (
    CUSTOMER_ID             NUMBER          PRIMARY KEY,
    FIRST_NAME              VARCHAR,
    LAST_NAME               VARCHAR,
    FULL_NAME               VARCHAR,
    PRIORITY_SCORE          VARCHAR(256),
    FIRST_ORDER             DATE,
    MOST_RECENT_ORDER       DATE,
    NUMBER_OF_ORDERS        NUMBER(18,0),
    CUSTOMER_LIFETIME_VALUE NUMBER(38,6),
    LAST_UPDATE_AT          TIMESTAMP_NTZ
) COMMENT = 'new ''description''';

-- COMMENT preserved from COLLATE_SHOP: 'DEMO ORDERS'
CREATE OR REPLACE TRANSIENT TABLE COLLATE_SE.ORDERS (
    ORDER_ID                NUMBER,
    CUSTOMER_ID             NUMBER,
    ORDER_DATE              DATE,
    STATUS                  VARCHAR,
    CREDIT_CARD_AMOUNT      NUMBER(38,6),
    COUPON_AMOUNT           NUMBER(38,6),
    BANK_TRANSFER_AMOUNT    NUMBER(38,6),
    GIFT_CARD_AMOUNT        NUMBER(38,6),
    AMOUNT                  NUMBER(38,6)
) COMMENT = 'DEMO ORDERS';

CREATE OR REPLACE TABLE COLLATE_SE.ORDER_ITEMS (
    ORDER_ITEM_ID   NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    ORDER_ID        NUMBER,
    PRODUCT_ID      NUMBER,
    QUANTITY        NUMBER,
    UNIT_PRICE      NUMBER(10,2),
    TOTAL_AMOUNT    NUMBER(10,2)
);

CREATE OR REPLACE TABLE COLLATE_SE.PRODUCTS (
    PRODUCT_ID      NUMBER       NOT NULL AUTOINCREMENT PRIMARY KEY,
    PRODUCT_NAME    VARCHAR,
    CATEGORY        VARCHAR,
    ECO_FRIENDLY    BOOLEAN,
    UNIT_PRICE      NUMBER(10,2)
);

CREATE OR REPLACE TABLE COLLATE_SE.PRODUCT_PERFORMANCE (
    PRODUCT_ID      NUMBER,
    PRODUCT_NAME    VARCHAR,
    TOTAL_ORDERS    NUMBER,
    TOTAL_REVENUE   NUMBER
);

CREATE OR REPLACE TABLE COLLATE_SE.CUSTOMER_LIFETIME_VALUE (
    CUSTOMER_ID             NUMBER,
    TOTAL_ORDER             NUMBER,
    TOTAL_REVENUE           FLOAT,
    AVERAGE_ORDER_VALUE     FLOAT,
    DAYS_SINCE_FIRST_ORDER  NUMBER,
    DAYS_SINCE_LAST_ORDER   NUMBER,
    CUSTOMER_TENUR          NUMBER,
    ORDER_FREQUENCY         NUMBER,
    SEGMENT                 VARCHAR(256)
);

-- ============================================================
-- 5. VIEWS  (pointing to COLLATE_SE tables, not COLLATE_SHOP)
-- ============================================================

CREATE OR REPLACE VIEW COLLATE_SE.STG_CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME) AS
    SELECT ID AS CUSTOMER_ID, FIRST_NAME, LAST_NAME
    FROM COLLATE_SE.RAW_CUSTOMERS;

CREATE OR REPLACE VIEW COLLATE_SE.STG_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS) AS
    SELECT ID AS ORDER_ID, USER_ID AS CUSTOMER_ID, ORDER_DATE, STATUS
    FROM COLLATE_SE.RAW_ORDERS;

-- RAW_PAYMENTS not exported from COLLATE_SHOP (stub view preserves schema for Collate metadata)
CREATE OR REPLACE VIEW COLLATE_SE.STG_PAYMENTS (PAYMENT_ID, ORDER_ID, PAYMENT_METHOD, AMOUNT) AS
    SELECT NULL::NUMBER AS PAYMENT_ID, NULL::NUMBER AS ORDER_ID,
           NULL::VARCHAR AS PAYMENT_METHOD, NULL::NUMBER AS AMOUNT
    WHERE 1=0;

CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER360 (
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, FULL_NAME, PRIORITY_SCORE,
    TOTAL_ORDERS, LIFETIME_VALUE, LAST_ORDER_DATE,
    CUSTOMER_TIER, ECO_PRODUCTS_PURCHASED
) AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.FULL_NAME,
    c.PRIORITY_SCORE,
    COUNT(DISTINCT o.ORDER_ID)    AS TOTAL_ORDERS,
    SUM(oi.TOTAL_AMOUNT)          AS LIFETIME_VALUE,
    MAX(o.ORDER_DATE)             AS LAST_ORDER_DATE,
    CASE
        WHEN SUM(oi.TOTAL_AMOUNT) > 200  THEN 'High Value'
        WHEN SUM(oi.TOTAL_AMOUNT) >= 50  THEN 'Medium Value'
        ELSE 'Low Value'
    END AS CUSTOMER_TIER,
    COUNT_IF(p.ECO_FRIENDLY)      AS ECO_PRODUCTS_PURCHASED
FROM COLLATE_SE.CUSTOMERS c
LEFT JOIN COLLATE_SE.ORDERS o     ON c.CUSTOMER_ID = o.CUSTOMER_ID
LEFT JOIN COLLATE_SE.ORDER_ITEMS oi ON o.ORDER_ID  = oi.ORDER_ID
LEFT JOIN COLLATE_SE.PRODUCTS p   ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.FULL_NAME, c.PRIORITY_SCORE;

-- Customer version views (V0-V9) -- same pattern, each adds one more column
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V0 AS SELECT CUSTOMER_ID FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V1 AS SELECT CUSTOMER_ID, FIRST_NAME FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V2 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V3 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V4 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER, MOST_RECENT_ORDER FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V5 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER, MOST_RECENT_ORDER, NUMBER_OF_ORDERS FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V6 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER, MOST_RECENT_ORDER, NUMBER_OF_ORDERS, CUSTOMER_LIFETIME_VALUE FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V7 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER, MOST_RECENT_ORDER, NUMBER_OF_ORDERS, CUSTOMER_LIFETIME_VALUE, LAST_UPDATE_AT FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V8 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER, MOST_RECENT_ORDER, NUMBER_OF_ORDERS, CUSTOMER_LIFETIME_VALUE, LAST_UPDATE_AT FROM COLLATE_SE.CUSTOMERS;
CREATE OR REPLACE VIEW COLLATE_SE.CUSTOMER_V9 AS SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, FIRST_ORDER, MOST_RECENT_ORDER, NUMBER_OF_ORDERS, CUSTOMER_LIFETIME_VALUE, LAST_UPDATE_AT FROM COLLATE_SE.CUSTOMERS;

-- ============================================================
-- 6. GRANT ACCESS TO SALES_ENGINEERS ROLE
-- ============================================================
GRANT USAGE ON SCHEMA CUSTOMERS.COLLATE_SE TO ROLE SALES_ENGINEERS;
GRANT SELECT ON ALL TABLES  IN SCHEMA CUSTOMERS.COLLATE_SE TO ROLE SALES_ENGINEERS;
GRANT SELECT ON ALL VIEWS   IN SCHEMA CUSTOMERS.COLLATE_SE TO ROLE SALES_ENGINEERS;
